import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/footer";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ethio Car Rental",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <Navbar />
        {children}
        <Footer />

        {/* Floating Call Button */}
        <div className="fixed bottom-6 right-6 z-50">
          <Link href="tel:+25191123456">
            <button className="bg-blue-600 text-white p-4 rounded-full shadow-lg hover:bg-blue-700">
<svg
  xmlns="http://www.w3.org/2000/svg"
  className="w-8 h-8"
  fill="none"
  viewBox="0 0 24 24"
  stroke="currentColor"
>
<path
  strokeLinecap="round"
  strokeLinejoin="round"
  strokeWidth="2"
/>
</svg>
            </button>
          </Link>
        </div>
      </body>
    </html>
  );
}
